---
- name: extract zipped artifact
  become: true
  unarchive:
    src: files/artifact.tar.gz
    dest: "/home/ubuntu/artifact.tar.gz"

- name: start backend
  become: true
  shell: |
    cd /home/ubuntu/
    tar -xvfz artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start